---
title: "R Notebook"
output: html_notebook
---

1. Conociendo los datos

1.1
```{r}
library(tidyverse)
```
1.2
```{r}
yearly <- read_csv('deaths_handwashing.csv')
```
1.3
```{r}
yearly
```

2. El alarmante número de muertes

2.1
```{r}
yearly <- yearly %>%
  mutate(proportion_deaths=deaths/births)
```
2.2
```{r}
yearly
```

3. Muerte en las clínicas

3.1 y 3.2
```{r}

ggplot(yearly, aes(x=year,y=proportion_deaths, color=clinic)) +
  geom_line()
```
4. Comienza el lavado de manos

4.1
```{r}

monthly <- read_csv('deaths_clinic_1.csv')

monthly
```
4.2
```{r}
monthly <- monthly %>%
  mutate(proportion_deaths=deaths/births)

```
4.3
```{r}

monthly %>%
  head()
```

5. El efecto del lavado de manos
5.1
```{r}
ggplot(monthly, aes(x=date,y=proportion_deaths)) +
  geom_line()

```
5.2
```{r}

ggplot(monthly, aes(x=date,y=proportion_deaths)) +
  geom_line() +
  labs(x="Fecha", y="Proporción de muertes por nacimientos",title = "Proporción de muertes a lo largo del tiempo")
```
6. Los resultados del lavado de manos

6.1
```{r}

monthly <- monthly %>%
  mutate (handwashing_started = ifelse (format(date,'%Y')>=1847, TRUE, FALSE))
```
6.2
```{r}
monthly
ggplot(monthly, aes(x=date,y=proportion_deaths,color=handwashing_started) ) +
  geom_line() 
```
6.3
```{r}

monthly
ggplot(monthly, aes(x=date,y=proportion_deaths,color=handwashing_started) ) +
  geom_line() +
  labs(x="Fecha", y="Proporción de muertes por nacimientos",title = "Proporción de muertes sin lavado de manos/con lavado de manos", color="Inicio lavado de manos")
```
7. ¿Más lavado de manos, menos muertes?

7.1
```{r}
monthly %>%
  group_by(handwashing_started) %>%
  summarise(mean_proportion_deaths=mean(proportion_deaths))

```
7.2
```{r}

month_summary <-monthly %>%
  group_by(handwashing_started) %>%
  summarise(mean_proportion_deaths=mean(proportion_deaths))
```

7.3
```{r}
month_summary

```

